# Generated by Django 5.2.12 on 2026-03-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('holiday', models.CharField(blank=True, max_length=200)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_power', models.BooleanField(default=False)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='cafe.tag')),
            ],
        ),
    ]
