# Generated by Django 5.2.12 on 2026-03-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_type', models.CharField(choices=[('main', 'メイン画像'), ('sub', 'サブ画像')], default='sub', max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe.cafe')),
            ],
        ),
    ]
