# Generated by Django 5.2.12 on 2026-03-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='image_url',
        ),
    ]
