# Generated by Django 5.2.12 on 2026-03-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_review_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
