# Generated by Django 5.2.12 on 2026-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_remove_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
