# Generated by Django 5.2.12 on 2026-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_cafe_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='menu1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='おすすめメニュー1'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='menu2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='おすすめメニュー2'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='menu3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='おすすめメニュー3'),
        ),
    ]
