# Generated by Django 5.2.12 on 2026-03-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_cafe_menu1_cafe_menu2_cafe_menu3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='catch_copy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cafe',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cafe',
            name='nearest_station',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
