# Generated by Django 5.2.12 on 2026-03-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_cafe_catch_copy_cafe_category_cafe_nearest_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='category',
        ),
    ]
